name: voice_call_application
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Authentication
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1

  # Database
  cloud_firestore: ^5.4.4
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4

  # WebRTC
  flutter_webrtc: ^0.12.5
  socket_io_client: ^2.0.3+1

  # Recording
  record: ^5.1.2
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1

  # Speech to Text
  speech_to_text: ^7.0.0

  # State Management
  provider: ^6.1.2

  # UI
  flutter_slidable: ^3.1.1
  intl: ^0.19.0

  # Utilities
  uuid: ^4.5.1
  shared_preferences: ^2.3.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# Override problematic Linux platform dependency
dependency_overrides:
  record_linux: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
