// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3BTLbWgFY2k4OQ3A6HkacQ1vMDCKijgM',
    appId: '1:395675541665:web:2312adcc85c23883fc50e0',
    messagingSenderId: '395675541665',
    projectId: 'voice-call-application-6d2f4',
    authDomain: 'voice-call-application-6d2f4.firebaseapp.com',
    storageBucket: 'voice-call-application-6d2f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkmSj27hpAINPBkVZ5SXtmb9MVfxE7dZ4',
    appId: '1:395675541665:android:def560c0f97afba2fc50e0',
    messagingSenderId: '395675541665',
    projectId: 'voice-call-application-6d2f4',
    storageBucket: 'voice-call-application-6d2f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR3tAUdkL4cS8FSnhoK1gT0RgkfixTocY',
    appId: '1:395675541665:ios:e8bb90fc2e426855fc50e0',
    messagingSenderId: '395675541665',
    projectId: 'voice-call-application-6d2f4',
    storageBucket: 'voice-call-application-6d2f4.firebasestorage.app',
    iosBundleId: 'com.example.voiceCallApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR3tAUdkL4cS8FSnhoK1gT0RgkfixTocY',
    appId: '1:395675541665:ios:e8bb90fc2e426855fc50e0',
    messagingSenderId: '395675541665',
    projectId: 'voice-call-application-6d2f4',
    storageBucket: 'voice-call-application-6d2f4.firebasestorage.app',
    iosBundleId: 'com.example.voiceCallApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3BTLbWgFY2k4OQ3A6HkacQ1vMDCKijgM',
    appId: '1:395675541665:web:cc876acea36b272efc50e0',
    messagingSenderId: '395675541665',
    projectId: 'voice-call-application-6d2f4',
    authDomain: 'voice-call-application-6d2f4.firebaseapp.com',
    storageBucket: 'voice-call-application-6d2f4.firebasestorage.app',
  );
}
